[project]
name = "steam-idle-bot"
version = "0.1.0"
description = "Steam Idle Bot with Trading Card Support"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cachetools==6.1.0",
    "certifi==2025.6.15",
    "charset-normalizer==3.4.3",
    "eventemitter==0.2.0",
    "gevent==25.5.1",
    "gevent-eventemitter==2.1",
    "greenlet==3.2.3",
    "idna==3.10",
    "protobuf==3.20.3",
    "pydantic==2.9.2",
    "pydantic-settings==2.6.1",
    "pycryptodomex==3.23.0",
    "requests==2.32.4",
    "rich==13.9.2",
    "six==1.17.0",
    "steam>=1.4.0,<1.5.0",
    "steamclient==1.2",
    "urllib3==2.5.0",
    "vdf==3.4",
    "zope-event==5.1",
    "zope-interface==7.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3",
    "pytest-cov>=5.0",
    "ruff>=0.6",
]
