title: Steam Idle Bot Docs
markdown: kramdown
theme: null
baseurl: ""
url: "https://idler.bebitterbebetter.com.br"
exclude:
  - ../.github
  - ../tests
  - ../src
  - ../*.py
  - vendor
  - node_modules
