name: Deploy site via SFTP

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-sftp.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: List built files (debug)
        run: |
          echo "Built files:" && ls -lah _site | sed -n '1,200p'

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: sftp
          local-dir: _site/
          server-dir: /home/u762591502/domains/bebitterbebetter.com.br/public_html/idler/
          dangerous-clean-slate: true
          log-level: verbose
