name: Deploy site via SFTP
# Requires repository secrets:
#   SFTP_SERVER: e.g. ftp.bebitterbebetter.com.br
#   SFTP_USERNAME: hosting username
#   SFTP_PASSWORD: hosting password
#   SFTP_REMOTE_DIR: e.g. /home/.../public_html/idler
#   SFTP_PORT: "21" for FTP or "22" for SFTP
# Optional:
#   LFTP_PARALLEL: number of parallel transfers (not used by this action by default)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-sftp.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: List built files (debug)
        run: |
          echo "Built files:" && ls -lah _site | sed -n '1,200p'

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ${{ secrets.SFTP_PORT == '21' && 'ftp' || 'sftp' }}
          port: ${{ secrets.SFTP_PORT }}
          local-dir: _site/
          server-dir: ${{ secrets.SFTP_REMOTE_DIR }}/
          dangerous-clean-slate: true
          log-level: verbose
