name: Deploy site via SFTP
# Requires repository secrets:
#   SFTP_SERVER: e.g. ftp.bebitterbebetter.com.br
#   SFTP_USERNAME: hosting username
#   SFTP_PASSWORD: hosting password
#   SFTP_REMOTE_DIR: e.g. idler (for subdomain deployment)
#   SFTP_PORT: "21" for FTP or "22" for SFTP

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - ".github/workflows/deploy-sftp.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: List built files (debug)
        run: |
          echo "Built files:" && ls -lah _site | sed -n '1,200p'

      - name: Show deploy target (non-sensitive)
        run: |
          echo "Protocol: FTP"
          echo "Server: ${SFTP_SERVER%%.*}... (masked)"
          echo "Port: ${SFTP_PORT:-21}"
          echo "Remote dir: $SFTP_REMOTE_DIR"
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_REMOTE_DIR: ${{ secrets.SFTP_REMOTE_DIR }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}

      - name: Validate required secrets
        shell: bash
        run: |
          fail=0
          if [ -z "$SFTP_SERVER" ]; then echo "::error title=Missing secret::SFTP_SERVER is not set"; fail=1; fi
          if [ -z "$SFTP_USERNAME" ]; then echo "::error title=Missing secret::SFTP_USERNAME is not set"; fail=1; fi
          if [ -z "$SFTP_PASSWORD" ]; then echo "::error title=Missing secret::SFTP_PASSWORD is not set"; fail=1; fi
          if [ -z "$SFTP_REMOTE_DIR" ]; then echo "::error title=Missing secret::SFTP_REMOTE_DIR is not set"; fail=1; fi
          if [ -z "$SFTP_PORT" ]; then echo "::warning title=Missing secret::SFTP_PORT::defaulting to 21 (FTP)"; fi
          if [ "$fail" = "1" ]; then exit 1; fi
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_REMOTE_DIR: ${{ secrets.SFTP_REMOTE_DIR }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.SFTP_PORT || '21' }}
          local-dir: _site/
          server-dir: ${{ secrets.SFTP_REMOTE_DIR }}/
          dangerous-clean-slate: true
          log-level: verbose
          timeout: 60000
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store

      - name: Upload built site as artifact (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: built-site
          path: _site/
